title: "Develop"
description: "I hate to go to work. I like to write this blog"
about: "I hate to go to work."
location: "Koaea"
email: conquerorj@naver.com
baseurl: ""
url: "https://angjoong.github.io/"
twitter_username:
github_username:

# google analytics tracking code, please change the value
g_analytics: "UA-72004048-3"

# language settings
isolang: de
close_btn: "Ausblenden"
home_btn: "Startseite"
first_btn: "Scala"
second_btn: "Effective Java"
imprint_btn: "Impressum"
name_badge: "Ein Artikel von"
rss_badge: "Feed abbonieren!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
